### ISSUE TITLE
build: investigate static binary

### ISSUE THREAD

**Issue by lucab** [coreos/torcx#26]
torcx is currently a dynamic binary, but we should investigate if it is possible to bring it back to a plain-static binary.

After initial investigation, the cgo bits seems to be coming from two of our dependencies:
 * containers/image: it links agains libgpgme. This can however be disabled via a buildtag (`containers_image_openpgp`)
 * viper: its dynamic configuration brings in cgo for inotify support. This doesn't seem to be configurable, but needs further investigation. We don't strictly rely on it, so we can possibly get rid of it alltogether.

Other: we may still need cgo for our own internal purposes (eg. mounting), in which case we'll just admit that torcx has to be a dynamic binary. This needs to be re-assed once we are close to features completeness.

**Comment by dongsupark** [comment]
I also think that torcx should be simply a static binary file. It's not fun to take care of dependent libraries at runtime.

As for libgpgme, it's already done, isn't it? Both `Makefile` and `scripts/build.sh` already have the buildtag `containers_image_openpgp`, which causes containers/image to be built without cgo. (= go-native)

As for viper, AFAIK torcx doesn't need to watch config changes that depends on fsnotify. So it's already possible to disable cgo, I suppose. I just tested torcx without cgo, it works fine.

Though I'm not sure if there will be other use cases in the future.

**Comment by lucab** [comment]
Yeah, libgpgme is already ok. viper is actually maybe overkill here, I'm actually considering to drop it completely. But yes, we definitely don't need the fsnotify part as you noticed (was it just fine with `CGO_ENABLED=0`?).

I wasn't spending too much effort on this right now as it could maybe get re-introduced later, but if it is a simple change and you already tried it, a PR is welcome!

**Comment by dongsupark** [comment]
@lucab Yep, it's just fine with CGO_ENABLED=0. I'll create a PR.
