### ISSUE TITLE
apply: only propagate assets specified in manifest

### ISSUE THREAD

**Issue by lucab** [coreos/torcx#29]
Currently, torcx is meant to propagate all relevant assets (binaries, units, etc) found in the addon images by default.

This means that it scans the unpack directory for the usual paths (`/bin/, /usr/bin/, `/lib/systemd/system/`, etc.) and propagates everything found in there. This is done in order to make building torcx images via ebuild as easy as possible.

However, when building images with binaries+libs, I realized that spurious binaries may get dragged in (e.g. `libseccomp` bringing `scmp_sys_resolver`) and multiple copies may end up in different archives, causing conflicts/issues in profiles with multiple images built this way.

An alternative approach would be to reserve for ourself some dedicated paths for lookups (e.g. `/torcx/bin/` for binaries, `/torcx/service/` for services, etc.) where to symlink/copy assets to be explicitely propagated.

This is the usual implicit-vs-explicit story where I made an initial call for the implicit side but I now have some doubts. Moving to an explicit reserved path means more logic in the building phase, thus /cc @euank @crawford for inputs.

**Comment by lucab** [comment]
> Would it be unreasonable to have the image-creator specify which assets should be exposed? It's the same effect as the /torcx paths, but it wouldn't require them putting the binaries in a specific location.

That would be the intent of symlinking into `/torcx/bin/`: leaving the binaries in the original place (eg. `/usr/bin/`) and only selectively propagating assets selected by the image-creator via symlinks.

However, I'm not sure what you are suggesting in details, i.e. where are you thinking to specify those assets. We now have plain tgz on disk (instead of OCI as in the original plan), so we don't have freeform annotations anymore. With a bit of stretch I can imagine moving the same information to xattrs (feasible, perhaps a bit painful, and will be lost on transit) or a manifest inside the tgz (at which point we are re-inventing ACI).

**Comment by euank** [comment]
I don't have a strong preference on the implicit/explicit here.

I do think it's likely we'll eventually run into information we want to represent that will seem hacky or be hard to represent implicitly though, unless we're very 

It might make sense to still ensure we keep to a format as simple as annotations are so we can trivially move them to OCI in the future.

**Comment by lucab** [comment]
Sounds good. Let's just reserve a `/torcx/` topdir for ourself and drop a simple `annotations.json` metadata file in there, which can be later converted to external annotations on the image manifest.

Initial proposal would be as
```json
{
  "kind":"torcx-annotations-v0",
  "value":{
    "com.coreos.torcx.bins":[
      "/bin/containers",
      "/bin/runc"
    ],
    "com.coreos.torcx.services":[
      "/usr/lib/systemd/system/"
    ]
  }
}
```

And we'll grow the set of known keys as much as we need, starting from binaries and systemd services. This can be later converted to OCI annotations by defining an appropriate flattening+delimiter for the arrays.

/cc @squeed

**Comment by squeed** [comment]
Seems reasonable, but I have to think about it for a bit.

Also, calling the systemd files "services" is a bit inaccurate, since we also might want to install networkd files, generators, or sysusers files.

**Comment by lucab** [comment]
Sorry if I wasn't clear, but by "services" I mean "systemd service units" only. I'd expect networks, sockets, timers, etc to have their own sections.

**Comment by lucab** [comment]
PR is up at https://github.com/coreos/torcx/pull/41.
