### ISSUE TITLE
Container Linux inclusion: Phase 0

### ISSUE THREAD

**Issue by euank** [coreos/torcx#47]
This is a tracking issue for an initial inclusion of torcx in the alpha channel of container linux.

This specifically tracks phase 0 with the scope of: the single default version of docker is packaged and shipped via torcx for the alpha channel.

This intentionally punts on packaging multiple versions or supporting the use of torcx beyond this one version.

The primary pieces to get ironed out here are building the docker package for torcx and adding that, plus torcx itself, to the alpha image.

@dm0- @lucab: this is meant as a tracking issue for the next alpha. If it's either too early or the wrong focus to try and shoot for this, please feel free to re-evaluate as appropriate.

**Comment by lucab** [comment]
Thanks, I would slightly adjust this for the next alphas:
 * CL-alpha 1423.0.0
    * [ ] start tagging torcx releases, ie. alpha.1
    * [ ] embed `torcx` and `torcx-generator` in OS `/usr` (running the generator but keeping `torcx` out of PATH until we stabilize CLI UX)
    * [ ] add some kola tests to ensure such a nop doesn't break the boot, nor regress later
    * [ ] build a docker version for torcx and perform manual checks, without shipping it in the base OS
 * CL-alpha 1437.0.0
    * [ ] get torcx to milestone alpha.2 and tag it
    * [ ] ship an empty vendor profile and a docker torcx package (unused by default but testable) in the OS, alongside normal docker binaries
    * [ ] add some more kola tests to make sure assets are properly propagated and functional
 * CL-alpha 1451.0.0
    * [ ] get torcx to milestone alpha.3 and tag it
    * [ ] stabilize CLI UX, feature-gate unstable parts and move torcx to PATH
    * [ ] ship a full profile to activate docker, hardcoded may be still left there or converted to symlinks
    * [ ] start acceptance tests

@dm0- this heavily depends on your progress and workload, so feel free to adjust my estimations.

@euank If everything goes well, I think in 3 or 4 cycles we could reach your phase0 goal.

You both should have permission in here to edit in place (let me know if not). I also added an [external/CL label](https://github.com/coreos/torcx/labels/external%2FCL) for this kind of mostly-distro items.

**Comment by lucab** [comment]
Cross-referencing: overlay integration https://github.com/coreos/coreos-overlay/pull/2567

**Comment by dm0-** [comment]
1423.0.0 contains the generator and an empty profile.  We didn't add any kola tests specific to torcx for this; we just verified none of the existing tests is affected and there are no errors in the journal.  The PR for the next alpha's goal is coreos/coreos-overlay#2585.

**Comment by lucab** [comment]
We got through all the milestones above, thus closing.
