### ISSUE TITLE
CL: introduce a status service

### ISSUE THREAD

**Issue by lucab** [coreos/torcx#51]
Before moving to generator, `torcx apply` used to have its own service whose status was used to signal sucsess/failure of torcx itself. As we don't have such a service, there is no quick way for the user to know when torcx setup fails.

CL should probably provide a small helper service/target which check for the presence of the seal file under `/run/metadata/torcx` and report success/failure appropriately. Bonus point, some way of bridging logs from the the generator run (they are already in journald, just not attached to any service).

@dm0- assigning this to you to solve as you think it suits better. I think it can be done with a single bash test-ifelse-exit, but we can also add a `torcx status` if you need some more complex logic.

**Comment by dm0-** [comment]
I've added a `torcx.target` to my torcx ebuild which seems to work.

```ini
[Unit]
Description=Verify torcx succeeded
DefaultDependencies=no
AssertPathExists=/run/metadata/torcx

[Install]
WantedBy=basic.target
```

I'll close this when it's included in the overlay, unless something more is required.

**Comment by lucab** [comment]
Similarly to https://github.com/coreos/torcx/pull/34, I'd likely include such units directly in here and then document what are such system-integration details as well.
