### ISSUE TITLE
Mounting docker.sock on containers

### ISSUE THREAD

**Issue by gogaEnrique** [coreos/torcx#77]
Hi,

Is there any way to mount and use docker's socket into a container? I tried it but when I call docker I get this message: 

> The program docker is managed by torcx, which did not run.

I read this but it doesn't say anything about the socket but it is a transient unit
https://groups.google.com/forum/#!topic/coreos-user/ilC6l0X5Hnw

Thank you!

**Comment by lucab** [comment]
What did you try to do? More specifically, what are you bindmouting and how are you calling docker?

**Comment by lucab** [comment]
Closing a stale ticket.

@gogaEnrique if you have further issues/details to report, please submit a ticket to https://github.com/coreos/bugs.
