### ISSUE TITLE
The program docker is managed by torcx, which did not run.

### ISSUE THREAD

**Issue by maticm** [coreos/torcx#86]
After spinning up a new server on Google Cloud Platform using CoreOS current stable image, I am unable to download some images using `google/cloud-sdk` image:
```
core@server ~ $ docker run --net=host -v /home/core/.config:/root/.config -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker google/cloud-sdk gcloud docker -- pull gcr.io/<valid full path>
The program docker is managed by torcx, which did not run.
```

**Comment by euank** [comment]
I've also got an issue / some discussion on the same topic over here: https://github.com/coreos/bugs/issues/2112.

I think this issue / discussion better fits over there since it's really an artifact of the wrapper script we ship, so I'm closing tihs in favor of that issue.
