### ISSUE TITLE
"torcx profile set-next" doesn't write trailing newline

### ISSUE THREAD

**Issue by bgilbert** [coreos/torcx#88]
From looking at the code, it appears that torcx properly handles a trailing newline when reading `next-profile`, but forgets to add one when writing it.

**Comment by lucab** [comment]
This is because we [specified](https://github.com/coreos/torcx/blob/a5f45b5abb54d194abc56655e24abe1deeb7c0f1/Documentation/design/schemas.md#profile-selector) it as:
> `/etc/torcx/profile`: single plaintext string, `EOF`-terminated

Would you prefer this to be more liberal and just trim whitespaces/newlines in excess?
/cc @euank for an additional datapoint

**Comment by bgilbert** [comment]
It appears the reader code is doing that already:

https://github.com/coreos/torcx/blob/0008a1459dd6fb8fa7ed137c60433b0e5b445e87/pkg/torcx/profile.go#L80

**Comment by lucab** [comment]
Yes, the reader is already more lenient in that regard. I was explicitly asking about the spec (and then the writer), but I just guess it's better to align all of those on the trimming behavior.
