### ISSUE TITLE
Torcx userland missing?

### ISSUE THREAD

**Issue by roffe** [coreos/torcx#94]
To my disappointment i learned that the torcx demo videos that has been published shows things not available to the users.

Lucab informed me there is no "userland" in the OS so one cannot reproduce the demo videos.

```
lucab [9:39 AM] 
there is no userland in the OS, yes

[9:39] 
but the generator is always running (edited)
```

https://asciinema.org/a/115034
https://asciinema.org/a/127682

Is there a ETA for when userland is added or does the user have to build CoreOS themselves to get the commands shown in the videos above?

**Comment by bgilbert** [comment]
I expect we'll add the userspace tool to Container Linux in the months ahead.  https://github.com/coreos/bugs/issues/2215 has additional context.

**Comment by roffe** [comment]
Thanks for clarification @bgilbert
